### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by javohirbekkhaydarov** [AxadjonovOyatillo21/Bookshelf-API#1]
Asssalomu Aleykum Oyatillo qanday siz bilan bog`lansak bo`ladi biror bir discordmi nima ishlatasiz agar raqamiz bo`lsa tashlab qo`ying yoki menga bir telfon qiling 915440658

**Comment by AxadjonovOyatillo21** [comment]
Va alaykum assalom!
Discordingiz bo'lsa tashlang.

вс, 1 янв. 2023 г. в 23:23, Javohirbek Khaydarov ***@***.***>:

**Comment by AxadjonovOyatillo21** [comment]
Oyatillo Akhadjonov#6134 - discord.

чт, 5 янв. 2023 г. в 12:19, Oyatillo Axadjonov <
***@***.***>:

**Comment by AxadjonovOyatillo21** [comment]
Va alaykum assalom!
Oyatillo Akhadjonov#6134 - discord.

**Comment by javohirbekkhaydarov** [comment]
javohirbekkhaydarov#8339
discordim
